server:
  port: 8081

chari:
  baas:
    base-url: ${CHARI_BASE_URL:https://sandbox.charimoney.com}
    api-key: ${CHARI_API_KEY:7ba0c.4M+dfiRv+jgSifrjXxJekMlA00+W39kCXyjkfqLAOZw4}
    principal-agent-id: ${CHARI_PRINCIPAL_AGENT_ID:1710301}
    webhook-secret: ${CHARI_WEBHOOK_SECRET:}
    timeout-ms: 10000
    card-funding:
      accept-url: ${CHARI_ACCEPT_URL:http://localhost:8081/test/chari/card/accept}
      decline-url: ${CHARI_DECLINE_URL:http://localhost:8081/test/chari/card/decline}
    webhook:
      enabled: true
      path: /webhooks/chari
    audit:
      enabled: true
      mask-sensitive: true

logging:
  level:
    com.github.hamzaelalaouiismaili.chari: INFO
    com.example.charitest: INFO